name: Build BlazorApp1
run-name: Building and executing the C# project in this repository
on: 
  push:
  workflow_dispatch: 

env:
  AZURE_WEBAPP_NAME: microtrac   # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './BlazorApp1/BlazorApp1/bin/Release/net8.0/publish'      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8.0.x'

jobs:
  Building-And-Executing-Project:
    runs-on: windows-latest
    steps:
      
    - uses: actions/checkout@v4
    
    # Setup .NET Core SDK
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
          dotnet-version: 8.0.x
          
    - name: dotnet build and publish
      run: |
          dotnet restore ./BlazorApp1/BlazorApp1.sln
          dotnet build --configuration Release ./BlazorApp1/BlazorApp1.sln
          dotnet publish LemonIndustries/LemonIndustries.sln
    - name: 'Web App Deployment'
      uses: azure/webapps-deploy@v3
      with: 
        app-name: 'microtrac' # Replace with your app name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
        package: './BlazorApp1/BlazorApp1/bin/Release/net8.0/publish'
